<?php


namespace Kyanag\Form\Tests\Components\Decorators;


use Kyanag\Form\Tests\ComponentTestCase;
use Kyanag\Form\Tests\Factory;

class ColumnDecoratorTest extends ComponentTestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->component = Factory::makeTableFactory()->createElement("decorator-column", [
            "colSize" => 1,
            'size' => ""
        ]);

        //var_dump($this->component);exit();
    }

    public function testRender(){
        $cases = [
            'col-1' => [
                "colSize" => 1,
                'size' => ""
            ],
            'col-md-2' => [
                'colSize' => 2,
                'size' => "md"
            ],
            'col-sm' => [
                'size' => "sm"
            ],
        ];

        foreach ($cases as $class => $properties){
            $columnDecorator = Factory::makeTableFactory()->createElement("decorator-column", $properties);

            $this->assertTrue(strpos($columnDecorator->render(), $class) !== false);
        }
    }

}