<?php


namespace Kyanag\Form\Tests\Supports;


use Kyanag\Form\Tests\TestCase;

class ComponentBuilderTest extends TestCase
{


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testMain(){
        $this->assertTrue(true);
    }
}