<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/29
 * Time: 17:45
 */

namespace Kyanag\Form\Fields;


class Radio extends Select
{
    public $subTemplate = '<div class="form-check form-check-inline">{input}{label}</div>';

    public $subAttributes = [
        'class' => [
            'form-check-input'
        ],
        'type' => "radio",
    ];

    public $labelAttributes = [
        'class' => ["col-sm-2", "col-form-label", "pt-0"],
    ];

    public $subLabelAttributes = [
        'class' => [
            'form-check-label'
        ],
    ];

    public function renderInput()
    {
        $options = [];
        foreach($this->options as $index => $option){
            $options[] = $this->renderOption($option, $index);
        }
        return implode("", $options);
    }

    public function renderLabel()
    {
        return parent::renderLabel(); // TODO: Change the autogenerated stub
    }

    protected function renderOption($option, $index){
        if(!isset($this->subAttributes['id'])) $this->subAttributes['id'] = $this->generateId() . "-{$index}";

        $this->subAttributes['name'] = $this->name;
        $this->subAttributes['value'] = $option['value'];
        $this->subAttributes['checked'] = $this->selected($option['value']);
        $this->subLabelAttributes['for'] = $this->subAttributes['id'];

        $parts = [
            '{input}' => "<input {$this->renderAttributes($this->subAttributes)}/>",
            '{label}' => "<label {$this->renderAttributes($this->subLabelAttributes)}>{$option['name']}</label>",
        ];
        unset($this->subAttributes['id']);
        return strtr($this->subTemplate, $parts);
    }
}