<?php


namespace Kyanag\Form\Tests\Components\Forms;


use Kyanag\Form\Tests\ComponentTestCase;
use Kyanag\Form\Tests\Factory;

class FormSectionTest extends ComponentTestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->component = $this->createElement("form-section", [], [

        ]);
    }

    public function testSetValue()
    {
        parent::testSetValue();

        $titleInput = $this->createElement("text", [
            'name' => "title",
            'label' => "标题"
        ]);


        $formSection = $this->createElement("form-section", [
            "valueDomain" => "post",
        ], [
            $titleInput
        ]);

        $formSection->setValue([
            'title' => "111",
        ]);

        $this->assertTrue($titleInput->getValue() === "111");
    }

}